### PR TITLE
(RO-4081) only run tasks to create network

### PR DESCRIPTION
**Pull request by phongdly**
Prior to this PR, CI passed the test step that creates network, but failed to run the next test of verifying the created network.

I still don't know why it happens.

The newly added `tags` in the `openstack-service-setup.yml` will allow us to run only tasks for creating network, to reduce the setup step significantly (from about 10 minutes to 32 seconds) because the `create image` task is not running. 

In this PR, only `create_networks` tags is included in the ansible-playbook running, also the work-around steps for REO-198 is no longer needed (the issue is still there but this time we only need to run create_networks tasks that have not been on the SUT previously)

### CODE REVIEW

**Comment by phongdly** [comment]
passed local test:
   ============================= test session starts ==============================
    platform linux2 -- Python 2.7.12, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
    rootdir: /root/github/rpc-openstack-system-tests/molecules/molecule-validate-neutron-deploy/molecule/default, inifile:
    plugins: testinfra-1.7.1, rpc-0.2.0
collected 3 items

    tests/test_10_network_setup.py .                                         [ 33%]
    tests/test_verify_networks_created.py ..                                 [100%]

     generated xml file: /root/github/rpc-openstack-system-tests/molecules/molecule-validate-neutron-deploy/molecule/default/test.xml
    ========================== 3 passed in 31.63 seconds ===========================
Verifier completed successfully.

**Comment by phongdly** [comment]
hmm.. it's weird, I thought I removed it :-)

**Comment by phongdly** [comment]
@johnduarte I think the file is removed in the PR

**Comment by johnduarte** [comment]
No changes have been pushed, so it is still there.

**Comment by phongdly** [comment]
it's removed in the original commit

**Comment by phongdly** [comment]
I will push a commit for adding .gitignore file

**Pull request merged**
